version: "3.8"
services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB: codelee_prod
      POSTGRES_USER: codelee-admin
      POSTGRES_PASSWORD: codelee-password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  server:
    build: .
    command: pnpm --filter codelee-server start:prod
    ports:
      - "3001:3001"
    env_file:
      - ./packages/codelee-server/.env.production
    environment:
      DATABASE_URL: postgresql://codelee-admin:codelee-password@db:5432/codelee_prod?schema=public
      NODE_ENV: production
    depends_on:
      - db

  web:
    build: .
    command: pnpm --filter codelee-web start
    ports:
      - "3000:3000"
    env_file:
      - ./packages/codelee-web/.env.production
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:3001/api
      NODE_ENV: production

volumes:
  db_data:
